# Generated by Django 4.2.10 on 2024-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='libelle',
            field=models.CharField(default='nom marque', max_length=50, unique=True),
        ),
    ]
